---
title: "თვისებრივი კონტენტ-ანალიზი (ფილიპ მაირინგი)"
description: |
  წარმოდგენილი სტატია აღწერს ტექსტის სისტემურ, ინსტრუქციებზე დაფუძნებულ ანალიზს,  რომელიც ცდილობს შეინარჩუნოს რაოდენობრივი კონტენტ-ანალიზის მეთოდოლოგიური ძლიერი მხარეები და გაავრცელოს ისინი თვისებრივი მონაცემთა ანალიზის პროცედურებზე.
author:
  - name: თემურ გუგუშვილი 
    url: https://example.com/norajones
    affiliation: Spacely Sprockets
    affiliation_url: https://example.com/spacelysprokets
  - name: თამუნა ჩხაიძე 
    url: https://example.com/norajones
    affiliation: Spacely Sprockets
    affiliation_url: https://example.com/spacelysprokets
date: 06-21-2022
output:
  distill::distill_article:
    self_contained: false
    toc: true
    toc_depth: 2
  
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

# Learn more about creating blogs with Distill at:
# https://rstudio.github.io/distill/blog.html

```


## აბსტრაქტი

წარმოდგენილი სტატია აღწერს ტექსტის სისტემურ, ინსტრუქციებზე დაფუძნებულ ანალიზს,  რომელიც ცდილობს შეინარჩუნოს რაოდენობრივი კონტენტ-ანალიზის მეთოდოლოგიური ძლიერი მხარეები და გაავრცელოს ისინი თვისებრივი მონაცემთა ანალიზის პროცედურებზე.

სტატიაში პირველ რიგში აღწერილია კონტენტ-ანალიზის განვითარების ისტორია და ახსნილია ანალიზის ძირითადი პრინციპები (ანალიზის ერთეული, ეტაპებიანი მოდელები (step models), კატეგორიებთან მუშაობა, სანდოობა და ვალიდობა). შემდეგ, ნაჩვენებია კონტენტანალიზი ცენტრალური პროცედურები, კატეგორიების ინდუქციური შექმნა, კატეგორიების დედუქციური გამოყენება. სტატიაში, ასევე წარმოდგენილია აღნიშნული ანალიზის ეტაპების განხორციელების მხარდამჭერი კომპიუტერული პროგრამები. და ბოლოს, განხილულია მიდგომის შეზღუდვები და შესაძლებლობები.


## 1. შესავალი

თვისებრივი კონტენტანალიზი (MAYRING, 1983; 7th edition 2000), როგორც ამ სტატიაშია წარმოდგენილი, ტექსტის სისტემური ანალიზის მრავალ ტექნიკას მოიცავს. ანალიზის ეს მეთოდი 20 წლის წინ ლონგიტიდური კვლევის [longitudinal study] ფარგლებში შეიქმნა, რომელიც უმუშევრობის ფსიქო-სოციალურ შედეგებს აღწერდა (ULICH, HAUSSER, MAYRING et al. 1985). აღნიშნული პროექტის ფარგლებში ჩავატარეთ 600-მდე ღია ინტერვიუ, დაგვიგროვდა 20 000-ზე მეტი გვერდი ტრანსკრიპტი, რომელიც თვისებრივი მიდგომით უნდა გაანალიზებულიყო.

წარმოდგენილი ანალიზის პროცედურების ძირითადი იდეაა კომუნიკაციის შესახებ მეცნიერების ფარგლებში განვითარებული რაოდენობრივი კონტენტანალიზის უპირატესობების შენარჩუნება და მათი გავრცელება თვისებრივ-ინტერპრეტაციული ანალიზის ეტაპებზეც.

დამატებითი ინფორმაცია რაოდენობრივი კონტენტანალიზის შესახებ ხელმისაწვდომია ონლაინ [ორიგინალ ტექსტში მითითებული ბმულები არ მუშაობს]. 

(თვისებრივი) კონტენტანალიზის ობიექტი შეიძლება იყოს ნებისმიერი ტიპის ჩაწერილი კომუნიკაცია (ინტერვიუს ტრანსკრიპტი, დისკურსები, დაკვირვების პროტოკოლი, ვიდეო ჩანაწერი, დოკუმენტები ...). კონტენტანალიზი არ აანალიზებს მხოლოდ მასალის ღია/გამოხატულ შინაარს - როგორც ამას მისი სახელი მიანიშნებს. ბეკერმა და ლისმანმა (1973) განასხვავეს შინაარსის ორი დონე: 1) ტექსტის თემა და ძირითადი იდეა, როგორც  ღია შინაარსი და 2) კონტექსტი, როგორც ფარული შინაარსი. გარდა ამისა, კონტენტანალიზის მიზანს წარმოადგენს მასალის ფორმალური ასპექტების ანალიზიც. როგორც ქვემოთაა აღწერილი, კონტენტანალიზი ტექსტს ათავსებს კომუნიკაციის მოდელში, რომლის ფარგლებშიც განსაზღვრავს ანალიზის მიზანს. ამ აზრს იზიარებს კრიპენდორფიც, რომელიც კონტენტანალიზს შემდეგნაირად განმარტავს: „კონტენტანალიზი იყენებს სანდო და ვალიდურ მეთოდს ტექსტიდან მისი წყაროს სხვა მდგომარეობებსა თუ მახასიათებლებზე სპეციფიკური დასკვნების გამოსატანად“ (KRIPPENDORFF 1969, გვ. 103).

თვისებრივი კონტენტ-ანალიზი აღნიშნული ჩარჩოს ფარგლებში განისაზღვრება, როგორც ემპირიული მიდგომა, მეთოდოლოგიით მართული ტექსტის ანალიზი კომუნიკაციის კონტექსტში,  რომელიც მიყვება კონტენტანალიზის ანალიტიკურ წესებს და ეტაპებიან მოდელს ნაჩქარევი გარაოდენობრივების გარეშე.


## 2. კონტენტანალიზის ისტორია
ჩვენ შეიძლება კონტენტანალიზის განვითარების ისტორიაში განსხვავებული ფაზები გამოვყოთ  (cf. MERTEN 1983; KRIPPENDORFF 1980; MAYRING 1994a):

- **წინამორბედები:** ჰერმენევტიკულ კონტექსტში (მაგ. ბიბლიის ინტერპრეტაცია) ტექსტის ანალიზისა და შედარების განსხვავებული მიდგომები არსებობს: დაწყებული გაზეთების ადრეული ანალიზიდან, გრაფოლოგიის^[თეორია, რომლის მიხედვითაც შესაძლებელია ადამიანის ხელნაწერის საშუალებით მისი ხასიათის დადგენა. (წყარო: ხელის შესწავლა ადამიანის ხასიათის დასადგენად. უნივერსალური ენციკლოპედიური ლექსიკონი : [3 ტომად] / შეადგინა ალექსანდრე ელერდაშვილმა. - I-ლი გამოც.. - [თბ.] : ფანტაზია, 2006. - 28სმ. [MFN: 136149])] პროცედურებისა თუ ზიგმუნდ ფროიდის სიზმრის ანალიზით დამთავრებული.
- **კომუნიკაციის თეორიული საფუძველი:** მეოცე საუკუნის 20-30-იან წლებში ამერიკის შეერთებულ შტატებში, პაულ ფ. ლაზარსფელდმა და ჰაროლდ დ. ლასველმა საფუძველი ჩაუყარეს რაოდენობრივი კონტენტანალიზის  შექმნას. ამავე საუკუნის 50-იან წლებში ამ მეთოდის შესახებ პირველი სახელმძღვანელო „კონტენტანალიზი კომუნიკაციის კვლევებში“[Content Analysis in Communication Research] გამოქვეყნდა ბერნარ ბერელსონის მიერ (Berelson 1952).
- **ინტერდისციპლინური გაფართოება და გამიჯვნა:** მეოცე საუკუნის 60-იან წლებში აღნიშნული მეთოდოლოგიური მიდგომა განვითარდა ლინგვისტიკაში, ფსიქოლოგიაში (cf. Rust 1983), სოციოლოგიაში, ისტორიაში, ხელოვნებაში და ა.შ. დაიხვეწა პროცედურები (მოერგო კომუნიკაციის სხვადასხვა მოდელს; განვითარდა არავერბალური ასპექტების ანალიზი, ნიშანთა შეუღლების ცხრილებით ანალიზი/კროსტაბულაციური ანალიზი; დაიწყო კომპიუტერული პროგრამების გამოყენება) (cf. Pool 1959; Gerbner, Holsti, Krippendorff, Paisley & Stone 1969).
- **თვისებრივი პერსპექტივიდან კრიტიკა:** მეოცე საუკუნის მეორე ნახევრიდან გაჩნდა კრიტიკული დამოკიდებულება ზედაპირული ანალიზის მიმართ ლატენტური/ფარული შინაარსისა და კონტექსტის გათვალისწინების გარეშე, რომელიც კეთდებოდა გამარტივებული და გამრუდებული გარაოდენობრივებით (Kracauer 1952). აღნიშნულს მოჰყვა კონტენტ-ანალიზის თვისებრივი მიდგომის შექმნა (Ritsert 1972; Mostyn 1985; Wittkowski 1994; Altheide 1996).


## 3. კონტენტ-ანალიზის ძირითადი იდეა 

თუ ჩვენ ვამბობთ, რომ თვისებრივმა კონტენტ-ანალიზმა რაოდენობრივი კონტენტ-ანალიზის უპირატესობები უნდა შეინარჩუნოს ტექსტის უფრო მეტი თვისებრივი ინტერპრეტაციისთვის, ისმის კითხვა - რა არის ეს უპირატესობები? მე მინდა ხაზი გავუსვა ოთხ  მათგანს:

- **მასალის (material) მორგება კომუნიკაციის მოდელზე:** უნდა განისაზღვროს კომუნიკაციის რომელ ნაწილზე დაყრდნობით მოხდება დასკვნების გაკეთება; იქნება ეს კომუნიკაციის აქტორი (მისი გამოცდილება, მოსაზრებები, გრძნობები), ტექსტის შექმნის გარემო, სოციალურ-კულტურული წარმომავლობა, თავად ტექსტი თუ შეტყობინების ეფექტი.
- **ანალიზის წესები:** მასალა (მაგ. ტექსტი) უნდა გაანალიზდეს ნაბიჯ-ნაბიჯ, მიყვებოდეს პროცედურულ წესებს, დაიყოს ტექსტი შინაარსობრივ, ანალიტიკურ ერთეულებად.

## ბიბლიოგრაფია
Altheide, D.L. (1996). Qualitative media analysis. Qualitative Research Methods Vol. 38. Thousand Oaks: Sage. 

Ballstaedt, S.-P.; Mandl, H.; Schnotz, W. & Tergan, S.-O. (1981). Texte verstehen, Texte gestalten. München: Urban & Schwarzenberg.

Bauer, J.; Qualmann, J.; Stadtmüller, G. & Bauer, H. (1998). Lebenslaufuntersuchungen bei Alzheimer-Patienten: Qualitative Inhaltsanalyse prämorbider Entwicklungsprozesse. In Kruse, A. (Ed.), Psychosoziale Gerontologie. Band 2: Intervention (pp.251-274). Göttingen: Hogrefe. 

Beck, K. & Vowe, G. (1995). Multimedia aus der Sicht der Medien. Argumentationsmuster und Sichtweisen in der medialen Konstruktion. Rundfunk und Fernsehen, 43, 549-563.

Becker, J. & Lißmann, H.-J. (1973). Inhaltsanalyse - Kritik einer sozialwissenschaftlichen Methode. Arbeitspapiere zur politischen Soziologie 5. München: Olzog. 

Berelson, B. (1952). Content analysis in communication research. Glencoe, Ill.: Free Press. 

Dijk van, T.A. (1980). Macrostructures. Hillsdale, N.J.: Erlbaum.
Dolde, C. & Götz, K. (1995). Subjektive Theorien zu Lernformen in der betrieblichen DV-Qualifizierung. Unterrichtswissenschaft, 23, 264-287.

Fielding, N.G. & Lee, R.M. (1998). Computer analysis and qualitative research. London: Sage. 

Gerbner, G.; Holsti, O.R.; Krippendorff, K.; Paisley, W.J.& Stone, Ph.J. (Eds.) (1969). The analysis of communication content. New York: Wiley. 

Gerwin, C. (1994). Streß in der Schule - Belastungswahrnehmung von Lehrerinnen und Lehrern. Zeitschrift für Pädagogische Psychologie, 8, 41-53. 

Huber, G.L. (Ed.) (1992). Qualitative Analyse. Computereinsatz in der Sozialforschung. München: Oldenbourg Verlag. 

Kracauer, S. (1952). The challenge of qualitative content analysis. Public Opinion Quarterly, 16, 631-642. 

Krippendorff, K. (1969). Models of messages: three prototypes. In G. Gerbner, O.R. Holsti, K. Krippendorff, G.J. Paisly & Ph.J. Stone (Eds.), The analysis of communication content. New York: Wiley. 

Krippendorff, K. (1980). Content analysis. An Introduction to its Methodology. Beverly Hills: Sage.

Mayring, Ph. (1994a). Qualitative Inhaltsanalyse. In A. Böhm, A. Mengel & T. Muhr (Eds.), Texteverstehen: Konzepte, Methoden, Werkzeuge (pp.159-176). Konstanz: Universitätsverlag. 
Mayring, Ph. (1994b). Qualitative Ansätze in der Krankheitsbewältigungsforschung. In E. Heim & M. Perrez, (Eds.), Krankheitsverarbeitung. Jahrbuch der Medizinischen Psychologie 10 (pp.38-48). Göttingen: Hogrefe. 
Mayring, Ph. (1996). Einführung in die qualitativer Sozialforschung. Eine Anleitung zu qualitativem Denken (3rd edition). Weinheim: Psychologie Verlags Union. 
Mayring, Ph. (2000). Qualitative Inhaltsanalyse. Grundlagen und Techniken (7th edition, first edition 1983). Weinheim: Deutscher Studien Verlag. 
Mayring, Ph.; König, J.; Birk, N. & Hurst, A. (2000). Opfer der Einheit. Eine Studie zur Lehrerarbeitslosigkeit in den neuen Bundesländern. Opladen; Leske & Budrich. 
Merten, K. (1983). Inhaltsanalyse. Einführung in Theorie, Methode und Praxis. Opladen: Westdeutscher Verlag. 
Mostyn, B. (1985). The content analysis of qualitative research data: A dynamic approach. In M. Brenner, J. Brown & D. Cauter (Eds.), The research interview (pp.115-145). London: Academic Press. 
Pool, J.d.S. (1959). Trends in content analysis. Urbana: University of Illinois Press.
Ritsert, J. (1972). Inhaltsanalyse und Ideologiekritik. Ein Versuch über kritische Sozialforschung. 
Frankfurt: Athenäum.
Rust, H. (1983). Inhaltsanalyse. Die Praxis der indirekten Interaktionsforschung in Psychologie und 
Psychotherapie. München: Urban & Schwarzenberg.
Schmitt, A. & Mayring, Ph. (2000, in press). Qualitativ orientierte Methoden. In J.H. Otto, H.A. Euler 
& H. Mandl. (Eds.), Handbuch Emotionspsychologie. Weinheim: Psychologie Verlags Union. 
Ulich, D.; Haußer, K.; Mayring, Ph.; Strehmel, P.; Kandler, M. & Degenhardt, B. (1985). Psychologie der Krisenbewältigung. Eine Längsschnittuntersuchung mit arbeitslosen Lehrern. Weinheim: Beltz. 
Vicini, S. (1993). Subjektive Beratungstheorien. Bernische ErziehungsberaterInnen reflektieren ihre Praxis. Bern: Lang. 
Weitzmann, E.A. & Miles, M.B. (1995). Computer Programs for Qualitativ Data Analysis. Newbury Park: Sage. 
Wittkowski, J. (1994). Das Interview in der Psychologie. Interviewtechnik und Codierung von Interviewmaterial. Opladen: Westdeutscher Verlag. 




## სტატიის შესახებ

### ავტორი

ფილიპ მაირინგი [Philipp MAYRING]

### ციტირება 

Mayring, Philipp (2000). Qualitative Content Analysis [28 paragraphs]. Forum Qualitative Sozialforschung / Forum: Qualitative Social Research, 1(2), Art. 20, DOI: [https://doi.org/10.17169/fqs-1.2.1089](https://doi.org/10.17169/fqs-1.2.1089). 

### თარგმანის ციტირება

Mayring, P. (2000). თვისებრივი კონტენტანალიზის (T. Gugushvili, T. Chkhaidze Trans.). https://doi.org/10.17169/fqs-1.2.1089 



